### ISSUE TITLE
Build error with generateTLSConfig

### ISSUE THREAD

**Issue by ocdtrekkie** [sdassow/wiking#12]
Trying to build, I got this error message:

`./server.go:543:27: s.generateTLSConfig undefined (type *Server has no field or method generateTLSConfig)`

**Comment by sdassow** [comment]
My bad, forgot the file.

**Comment by ocdtrekkie** [comment]
Thanks! I'll try again today hopefully. (A sad thing is that I didn't actually need TLS to work, but it wouldn't build without it.)

**Comment by sdassow** [comment]
On the other hand HTTP/2.0 would be more tricky to get going because of the certificate setup.

**Comment by sdassow** [comment]
Thanks for reporting! I do have to make sure I don't break the build in such a way.
