### ISSUE TITLE
Request: Option to disable rebind protection

### ISSUE THREAD

**Issue by ocdtrekkie** [sdassow/wiking#13]
I tried setting up my Sandstorm package using your fork, and immediately hit the error message created here: https://github.com/sdassow/wiking/commit/9acf57c2c97aaa2e8096e18306204a271bd7096e

Unfortunately, I don't believe there's a viable hostname I can provide: Each time a given instance of an app is loaded in Sandstorm, it's hosted on an unguessable hostname, and the hostname is not available to the application in the sandbox. I was wondering whether or not this protection was something you would consider making possible to disable, in the scenario that the app lives inside a sandbox that is managing many security protections itself.

**Comment by sdassow** [comment]
It is now optional. With an empty hosts list the rebind protection is not enabled anymore.

**Comment by ocdtrekkie** [comment]
Is there a way to set an environment variable to be empty and it still be recognized by the app? I tried `export WIKING_HOSTS=""`
