### ISSUE TITLE
Suggestion: Display the page title somewhere

### ISSUE THREAD

**Issue by ocdtrekkie** [sdassow/wiking#14]
I thought this was a bit odd upstream, people were confused the header just says "Wiki", and not like... the title of the page. The "Wiki" link acts as a home button, so that probably should remain, but pages should probably display the page title somewhere.

(Unless we imagine the page title should be placed "in-page" with Markdown... if this is true though, perhaps a new page should pre-fill that in the text box, so people know it's expected?)

**Comment by sdassow** [comment]
Fully agree and had similar thoughts already; thanks for the reminder/ticket :-)
